/* Generated by           cobc 4.0-early-dev.0 */
/* Generated from         server.cob */
/* Generated at           Jan 28 2026 19:49:30 */
/* GnuCOBOL build date    Sep 19 2022 04:28:17 */
/* GnuCOBOL package date  Jun 06 2020 20:56:36 UTC */
/* Compile command        cobc -x -free -g -debug -o server-cobol -lm server.cob c_helpers.o cob_helpers.o firestore_client.o mcpc/src/libmcpc.a */

/* Program local variables for 'check_db_cb_impl' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_impl_check_db;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* WORKING-STORAGE Data */
static int	b_58;	/* RETURN-CODE */

/* End of WORKING-STORAGE data */


/* Local Fields */
static cob_field f_64	= {8, NULL, &a_2};	/* tool-ptr */
static cob_field f_65	= {8, NULL, &a_2};	/* ucbr-ptr */

/* End of fields */

