/* Generated by           cobc 4.0-early-dev.0 */
/* Generated from         server.cob */
/* Generated at           Jan 28 2026 19:49:30 */
/* GnuCOBOL build date    Sep 19 2022 04:28:17 */
/* GnuCOBOL package date  Jun 06 2020 20:56:36 UTC */
/* Compile command        cobc -x -free -g -debug -o server-cobol -lm server.cob c_helpers.o cob_helpers.o firestore_client.o mcpc/src/libmcpc.a */

/* Program local variables for 'get_product_by_id_cb_impl' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_mcpc_tool_get_tpropval_u8str;
static cob_call_union	call_mcpc_ucbr_toolcall_add_errmsg_printf8;
static cob_call_union	call_impl_get_product_by_id;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[5];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* WORKING-STORAGE Data */
static int	b_88;	/* RETURN-CODE */
static cob_u8_t	b_94[3] __attribute__((aligned));	/* prop-name */
static cob_u8_t	b_95[4096] __attribute__((aligned));	/* id-buffer */
static cob_u8_t	b_96[8] __attribute__((aligned));	/* id-len */
static cob_u8_t	b_97[8] __attribute__((aligned));	/* id-cap */
static cob_u8_t	b_98[4] __attribute__((aligned));	/* call-res */
static cob_u8_t	b_99[30] __attribute__((aligned));	/* err-msg */

/* End of WORKING-STORAGE data */


/* Local Fields */
static cob_field f_94	= {3, b_94, &a_1};	/* prop-name */
static cob_field f_95	= {4096, b_95, &a_1};	/* id-buffer */
static cob_field f_96	= {8, b_96, &a_7};	/* id-len */
static cob_field f_97	= {8, b_97, &a_7};	/* id-cap */
static cob_field f_98	= {4, b_98, &a_3};	/* call-res */
static cob_field f_99	= {30, b_99, &a_1};	/* err-msg */
static cob_field f_100	= {8, NULL, &a_2};	/* tool-ptr */
static cob_field f_101	= {8, NULL, &a_2};	/* ucbr-ptr */

/* End of fields */

