def make_sandwich():
    print("   ______")
    print("  /     /")
    print(" /_____/|")
    print("(      )|")
    print("|______|/")
    print("   | |")
    print("   |_|")
    print("")
    print("Here is your digital sandwich!")
    print("      __________")
    print("     /         /")
    print("    /  Bread  /")
    print("   /_________/")
    print("  | Letuce  |")
    print("  | Tomato  |")
    print("  |  Meat   |")
    print("  | Cheese  |")
    print("  |_________|")
    print(" /         /")
    print("/  Bread  /")
    print("/_________/ ")

if __name__ == "__main__":
    make_sandwich()
