# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger'
gem 'mcp'

group :development, :test do
  gem 'rspec'
  gem 'rubocop'
end

gem 'google-cloud-firestore', '~> 2.15'

gem 'dotenv', '~> 3.2'
