(load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
(ql:quickload :40ants-mcp :silent t)
(let ((sym (find-symbol "SERVER-TOOLS-COLLECTIONS" :40ants-mcp/server/definition)))
  (format t "Symbol: ~A~%" sym)
  (format t "Bound? ~A~%" (boundp sym))
  (format t "Fbound? ~A~%" (fboundp sym))
  (when (boundp sym)
    (format t "Value: ~A~%" (symbol-value sym))))
(uiop:quit)